Adding Protein Structure Prediction related functionality
BiomedSciAI/fuse-drug pull request #1
Opened 2023-02-26 11:12 UTC by YoelShoshan

2023-02-26 12:10 UTC, alex-golts requested changes
Looks good mostly. See some small comments inline.
Also, unless I missed it, shouldn't there be some code that uses all these test data files. are you planning to add tests/examples?

2023-02-26 12:10 UTC, alex-golts commented on fusedrug/data/protein/structure/structure_io.py
> +    # with open(filename,'rt') as f:
remove

2023-02-26 12:10 UTC, alex-golts commented on fusedrug/data/protein/structure/structure_io.py
> +    #parser = MMCIFParser(QUIET=False)
remove

2023-02-26 12:10 UTC, alex-golts commented on fusedrug/data/protein/structure/structure_io.py
> +def save_pdb_file(
can you point to url that explains these terms like atom14, b_factors...

2023-02-27 07:05 UTC, YoelShoshan commented
> Looks good mostly. See some small comments inline. Also, unless I missed it, shouldn't there be some code that uses all these test data files? are you planning to add tests/examples?

Thanks!
Currently most (or possibly all) of the code that uses the test data is found in the jupyter notebooks, we should definitely add more test, I agree!

2023-02-27 07:57 UTC, alex-golts approved these changes

2023-03-01 08:08 UTC, mosheraboh approved these changes
Thanks Yoel.
I found some of those functions very useful when I implemented my dataset!
Please make sure we add the new dependencies to the requirements file.
(When I've tried it, I saw that openfold also missed a few - so I suggest to recreate env and to check it) 
Why did you add the examples from the data to fusedrug?
Is there a demo or test in fusedrug that use it?

2023-03-06 19:14 UTC, YoelShoshan commented on fusedrug/data/protein/structure/sabdab.py
> +        path = os.path.join(os.environ['SABDAB_DIR'],'sabdab_summary_all.tsv')
Do you mean a relative filename? because the function already can get a full path

2023-03-06 19:20 UTC, YoelShoshan commented
> tests

I think that I mostly use the test data in example jupyter notebooks, I'll check

2023-03-06 19:20 UTC, merged

2023-03-07 10:18 UTC, mosheraboh commented
> > tests
> 
> I think that I mostly use the test data in example jupyter notebooks, I'll check

If the notebook is not in fusedrug. I suggest moving it to the notebook repo.

2023-03-07 10:22 UTC, mosheraboh commented on fusedrug/data/protein/structure/sabdab.py
> +        path = os.path.join(os.environ['SABDAB_DIR'],'sabdab_summary_all.tsv')
I mean that the name of the summary table might be different (for example, the table of a summary table with affinity only has a different name)