Add tokens `<CORRUPTED_AREA_START>` & `<CORRUPTED_AREA_END>`
BiomedSciAI/fuse-drug pull request #110
Opened 2024-03-07 14:20 UTC by SagiPolaczek

2024-03-07 15:09 UTC, floccinauc requested changes
Looks good - just add the new tokens to bmfm_modular_tokenizer and bmfm_extended_modular_tokenizer, and make sure they're mapped to the same indices (they should do that automatically, but check just in case)

2024-03-07 19:02 UTC, floccinauc requested changes
All's good, except for one start-end token switch you missed (marked by comment)

2024-03-07 19:02 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/pretrained_tokenizers/bmfm_extended_modular_tokenizer/gene_tokenizer.json
> +      "id": 290,
You missed one: _END> should be 291

2024-03-07 19:57 UTC, SagiPolaczek commented on fusedrug/data/tokenizer/modulartokenizer/pretrained_tokenizers/bmfm_extended_modular_tokenizer/gene_tokenizer.json
> +      "id": 290,
Fixed

2024-03-10 07:08 UTC, floccinauc approved these changes
LGTM

2024-03-10 08:50 UTC, merged