Special token script and new gene tokenizer
BiomedSciAI/fuse-drug pull request #116
Opened 2024-03-18 10:23 UTC by matanninio

This PR ended up bigger then I had wanted.  It includes the following:
1. cleanup of files that slipped in
2. added a script to add special tokens to all tokenizers in one go
3. added configs for all the modular tokenizers (until now we only had a config for the first and then "add tokenizer" configs to add cell type and genes
4. added verbose setting to tests so tests do not print unless asked
5. replaced the gene list with a new one, extended the max token id to 100,000 and rebuilt

2024-03-19 09:13 UTC, floccinauc requested changes
Looks good overall. Please see comments inline (ping me when you have the time)

2024-03-19 09:13 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/create_multi_tokenizer.py
> +    verbose: bool = False,
Maybe let's keep to the modular tokenizer verbosity format - integer (0, 1,...), so verbose=0 will be the same as your verbose - False, and verbose of 1 and above - your True?

2024-03-19 09:13 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/create_multi_tokenizer.py
> +    verbose: bool = False,
This will also make things simpler down the road when we call encode_list

2024-03-19 09:13 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/pretrained_tokenizers/bmfm_extended_modular_tokenizer/cell_attributes_tokenizer.json
> +      "<49>": 333,
Why do we need numbers? Can't we just use digits? Like <1>, <0> instead of <10>?

2024-03-19 09:13 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/pretrained_tokenizers/bmfm_extended_modular_tokenizer/cell_attributes_tokenizer.json
> +      "<49>": 333,
In any case, I'm not sure special tokens is the place for integers. We only have 500 special tokens, and this is eating them up...

2024-03-19 09:13 UTC, floccinauc commented on fusedrug/data/tokenizer/modulartokenizer/tests/test_modular_tokenizer.py
> +    def setUp(self, config_holder: ConfigHolder = None, verbose: bool = False) -> None:
Same as above - consider making 'verbose' integer

2024-03-19 15:35 UTC, matanninio commented
cleared and streamlined.

2024-03-20 11:35 UTC, floccinauc approved these changes
LGTM

2024-03-20 13:11 UTC, merged