Added Issue Templates and also refactored some code.
BiomedSciAI/fuse-drug pull request #69
Opened 2023-07-05 09:58 UTC by Sai-Suraj-27

Added ISSUE TEMPLATES to fix issue #13 and refactored some code to make it better and more readable.

2023-07-08 09:38 UTC, Sai-Suraj-27 commented
@SagiPolaczek sir, Can you review this?

2023-07-08 10:14 UTC, SagiPolaczek commented
@Sai-Suraj-27  Sure! Sorry for the delay, I missed the notification.

Also I'll take this opportunity to test some tool I encountered lately: @CodiumAI-Agent

2023-07-08 10:15 UTC, CodiumAI-Agent commented
Preparing review...

2023-07-08 10:15 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** Adding issue templates and refactoring code
- 🔍 **Description and title:** Yes
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ✨ **Minimal and focused:** No, because the PR is doing two different things: adding issue templates and refactoring code. These should be split into two separate PRs for clarity and ease of review.
- 🔒 **Security concerns:** No, because the changes in this PR do not introduce any new functionalities that could potentially lead to security vulnerabilities.
## PR Feedback

- 💡 **General PR suggestions:** The PR should be split into two separate PRs: one for adding issue templates and another for refactoring the code. This will make it easier for reviewers to understand and review the changes. Also, it's recommended to add tests to verify the refactored code.

- 🤖 **Code suggestions:**


  - **relevant file:** fusedrug/data/interaction/drug_target/datasets/dti_binding_dataset.py
   **suggestion content:** Consider using more descriptive error messages. Instead of 'splits_tsv was provided but no use_folds provided', you could say 'splits_tsv was provided but use_folds is missing. Both are required for the operation.' [important]


  - **relevant file:** fusedrug/data/molecule/smi_character_histogram.py
   **suggestion content:** Consider adding a comment explaining the use of the '|=' operator for updating the total_characters_counter. This will make the code more readable for those unfamiliar with this operator. [medium]


  - **relevant file:** fusedrug_examples/interaction/drug_target/affinity_prediction/bimodal_mca_PPI/runner_PPI.py
   **suggestion content:** Consider removing the commented out import statement 'import tensorflow as tf' if it's not needed. [medium]


  - **relevant file:** fusedrug/data/molecule/tokenizer/build_molecule_tokenizer_with_predefined_vocab.py
   **suggestion content:** Consider removing the commented out code 'Split(pattern='.', behavior='isolated').pre_tokenize_str('blah')' if it's not needed. [medium]


### How to use
> Tag me in a comment '@CodiumAI-Agent' to ask for a new review after you update the PR.
> You can also tag me and ask any question, for example '@CodiumAI-Agent is the PR ready for merge?'

2023-07-08 10:28 UTC, SagiPolaczek requested changes
Thanks @Sai-Suraj-27 for your contribution!  😄 

Please see two minors inlines

2023-07-08 10:28 UTC, SagiPolaczek commented on fusedrug/data/molecule/smi_character_histogram.py
> +        total_characters_counter |= curr_counter
Although both are equivalent lets stay with `.update()` for better readability by the reader

2023-07-08 10:28 UTC, SagiPolaczek commented on .github/workflows/ISSUE_TEMPLATE/---bug-report.md
> +---
Let's proceed with moving the templates under the `.github/ISSUE_TEMPLATE` directory, please. Just to be consistent with other projects.

2023-07-08 11:20 UTC, SagiPolaczek approved these changes
Thanks! LGTM!

2023-07-09 06:18 UTC, SagiPolaczek commented
Closes #13

2023-07-09 06:18 UTC, merged